export interface Product{
    _id?: string;
    name:string,
    description:string,
    shortDescription: string,
    price:number,
    discount:number,
    images: string[],
    categoryId:string,
    isFeatured: boolean,
    isNewProduct:boolean,
    customizations: String,
    productDimensions: String,
    weight: Number,
    material: String,
    color: String,
    care: String,
    shape: String,
    finishType: String,
}